
title: 喵了个咪的
email: 喵喵？
description: >- # this means to ignore newlines until "baseurl:"
  我是喵喵，卖萌为生
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhongsiyuan.live" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  blur1206

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

author:
  name: "Zhong Siyuan"
  email: ""
  url: "https://zhongsiyuan.live"

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

custom_header: false
custom_nav_footer: false
reverse: false
